--SQL ADVANCE CASE STUDY 


--Q-1-- BEGIN

SELECT distinct(State)  FROM [dbo].[DIM_LOCATION] L
INNER JOIN [dbo].[FACT_TRANSACTIONS] T
ON L.IDLocation =T.IDLocation
where date >='01-01-2005'

--Q-1--END

--Q-2--BEGIN



SELECT  STATE, count(Quantity)  FROM [dbo].[FACT_TRANSACTIONS] T
INNER JOIN [dbo].[DIM_LOCATION] L
ON T.IDLocation=L.IDLocation
inner join [dbo].[DIM_MODEL] D
ON D.IDModel=T.IDModel
INNER JOIN [dbo].[DIM_MANUFACTURER]M
ON M.IDManufacturer=D.IDManufacturer
WHERE COUNTRY ='US' AND Manufacturer_Name = 'Samsung'
group by STATE 
ORDER BY count(Quantity) desc

--Q-2--END

--Q-3--BEGIN


SELECT  IDMODEL,ZIPCODE,STATE ,COUNT(IDCUSTOMER)  OVER(PARTITION BY IDMODEL,ZIPCODE,STATE) AS 'NUMBER OF CUSTOMERS' FROM [dbo].[FACT_TRANSACTIONS]T
INNER JOIN [dbo].[DIM_LOCATION] L
ON T.IDLocation=L.IDLocation


--Q-3--END

--Q-4--BEGIN

 
 SELECT  MIN(UNIT_PRICE)AS PRICE , Manufacturer_Name FROM [dbo].[DIM_MODEL] M
 INNER JOIN [dbo].[DIM_MANUFACTURER] F
 ON M.IDManufacturer=F.IDManufacturer
 group by Manufacturer_Name
 order by MIN(UNIT_PRICE)

 --Q-4--END

 --Q-5--BEGIN
 
 
SELECT  MODEL_NAME,AVG(UNIT_PRICE)
FROM [dbo].[DIM_MODEL]  
WHERE  exists (select  DISTINCT top 5 Manufacturer_Name, count(QUANTITY)  OVER(PARTITION BY Manufacturer_Name ) AS 'SALES QUANTITY' FROM [dbo].[DIM_MODEL]M 
INNER JOIN [dbo].[DIM_MANUFACTURER]F
ON F.IDManufacturer=M.IDManufacturer
INNER JOIN [dbo].[FACT_TRANSACTIONS]T 
ON T.IDModel=M.IDModel)
GROUP BY MODEL_NAME
ORDER BY AVG(UNIT_PRICE)

--Q-5--END


--Q-6--BEGIN

SELECT DISTINCT CUSTOMER_NAME , AVG(TOTALPRICE)  AS 'AVERAGE PRICE' FROM [dbo].[DIM_CUSTOMER]C
INNER JOIN [dbo].[FACT_TRANSACTIONS]T
ON C.IDCustomer=T.IDCustomer
INNER JOIN [dbo].[DIM_DATE]D
ON D.DATE=T.Date
WHERE YEAR=2009 
GROUP  BY CUSTOMER_NAME 
HAVING AVG(TOTALPRICE) > 500

--Q-6--END

--Q-7--BEGIN

SELECT J.MODEL_NAME FROM (SELECT M.MODEL_NAME,M.TOTAL_SALES FROM 
(SELECT TOP 5 A.MODEL_NAME , SUM(QUANTITY) AS TOTAL_SALES ,YEAR(DATE) AS YEAR FROM [dbo].[DIM_MODEL] A,
[dbo].[FACT_TRANSACTIONS] B
WHERE A.IDModel=B.IDModel AND YEAR(DATE) =2008
GROUP BY A.MODEL_NAME , YEAR(DATE)
ORDER BY TOTAL_SALES DESC)M
INNER JOIN 
(SELECT TOP 5 A.MODEL_NAME,SUM(QUANTITY) AS TOTAL_SALES, YEAR(DATE) AS YEAR
FROM [dbo].[DIM_MODEL] A,[dbo].[FACT_TRANSACTIONS] B
WHERE A.IDMODEL =B.IDModel AND YEAR(DATE) =2009
GROUP BY A.Model_Name,YEAR(DATE)
ORDER BY TOTAL_SALES DESC) N
ON M.MODEL_NAME = N.MODEL_NAME
GROUP BY M.MODEL_NAME,M.TOTAL_SALES) J
INNER JOIN 
(SELECT TOP 5 A.MODEL_NAME,SUM(QUANTITY) AS TOTAL_SALES,YEAR(DATE) AS 
YEAR FROM [dbo].[DIM_MODEL] A,
[dbo].[FACT_TRANSACTIONS] B
WHERE A.IDModel=B.IDModel
AND YEAR(DATE) =2010
GROUP BY Model_Name,YEAR(DATE)
ORDER BY TOTAL_SALES DESC) H
ON J.MODEL_NAME =H.Model_Name
GROUP BY J.MODEL_NAME


--Q-7--END

--Q-8--BEGIN
SELECT * FROM 
(SELECT TOP 1 MANUFACTURER_NAME , (N.SALES) AS SALES FROM
(SELECT C.MANUFACTURER_NAME, SUM(QUANTITY) AS SALES FROM 
FACT_TRANSACTIONS A,DIM_MODEL B,DIM_MANUFACTURER C
WHERE A.IDModel=B.IDModel AND B.IDManufacturer=C.IDManufacturer AND  YEAR(DATE)=2009
GROUP BY C.MANUFACTURER_NAME)N
WHERE N.SALES < (SELECT MAX(SALES) FROM 
(SELECT C.MANUFACTURER_NAME ,SUM(QUANTITY) AS SALES FROM FACT_TRANSACTIONS A,DIM_MODEL B,DIM_MANUFACTURER C
WHERE A.IDModel=B.IDModel  AND B.IDManufacturer=C.IDManufacturer AND  YEAR(DATE)=2009
GROUP BY C.MANUFACTURER_NAME)S)
ORDER BY SALES DESC) T09,
(SELECT TOP 1 N.MANUFACTURER_NAME,(N.SALES) AS SALES FROM 
(SELECT C.MANUFACTURER_NAME,SUM(QUANTITY) AS SALES
FROM FACT_TRANSACTIONS A,DIM_MODEL B,DIM_MANUFACTURER C
WHERE A.IDModel=B.IDModel AND B.IDManufacturer=C.IDManufacturer AND YEAR(DATE)=2010
GROUP BY C.MANUFACTURER_NAME)N
WHERE N.SALES < 
(SELECT MAX(SALES) FROM 
(SELECT C.MANUFACTURER_NAME,SUM(QUANTITY) AS SALES FROM FACT_TRANSACTIONS A,DIM_MODEL B, DIM_MANUFACTURER C
WHERE A.IDMODEL=B.IDModel AND B.IDManufacturer=C.IDManufacturer AND YEAR(DATE) =2010
GROUP BY C.Manufacturer_Name) S)
ORDER BY SALES DESC) T10



--Q-8--END


--Q-9--BEGIN


SELECT DISTINCT C.IDMANUFACTURER, C.MANUFACTURER_NAME FROM FACT_TRANSACTIONS A,DIM_MODEL B,DIM_MANUFACTURER C
WHERE A.IDMODEL=B.IDModel AND B.IDManufacturer=C.IDManufacturer
AND YEAR(DATE) IN (2010)
AND C.Manufacturer_Name NOT IN (SELECT DISTINCT C.MANUFACTURER_NAME
FROM FACT_TRANSACTIONS a, DIM_MODEL b,DIM_MANUFACTURER c
where a.IDModel=b.IDModel and b.IDManufacturer=c.IDManufacturer
and year(date) in (2009))

--Q-9--END


--Q-10--BEGIN

SELECT * ,((CHANGE_ANG_SPEND)*100/AVERAGE_SPEND) AS PERCENT_CHANGE FROM
(SELECT * , LAG(AVERAGE_SPEND,1)  OVER (PARTITION BY YEAR ORDER BY AVERAGE_SPEND ) AS CHANGE_ANG_SPEND FROM 
(SELECT CUSTOMER_NAME , YEAR, AVG(TOTALPRICE) AS AVERAGE_SPEND , AVG(QUANTITY) AS AVERAGE_QUANTITY_ORDERED FROM FACT_TRANSACTIONS
LEFT JOIN DIM_MODEL
ON FACT_TRANSACTIONS.IDModel=DIM_MODEL.IDModel
LEFT JOIN DIM_DATE
ON FACT_TRANSACTIONS.Date =DIM_DATE.DATE
LEFT JOIN DIM_MANUFACTURER
ON DIM_MODEL.IDManufacturer=DIM_MANUFACTURER.IDManufacturer
LEFT JOIN DIM_CUSTOMER
ON FACT_TRANSACTIONS.IDCustomer=DIM_CUSTOMER.IDCustomer
GROUP BY Customer_Name,YEAR) P)Q


--Q-10--END